theme: jekyll-theme-cayman
site_name: Robert S. Harbert, Ph.D.
gems:
  - jekyll-seo-tag
twitter:
  username: robharbert
social:
  name: Rob Harbert
  links:
    - https://twitter.com/robharbert
    - https://www.linkedin.com/in/robert-harbert-575175129/
    - https://github.com/rsh249
