theme: jekyll-theme-cayman
og:
    site_name: Dr. Robert S. Harbert, Ph.D.
    description: Public page
    title: Personal page of Rob Harbert
gems:
  - jekyll-seo-tag
twitter:
  username: robharbert
social:
  name: Rob Harbert
  links:
    - https://twitter.com/robharbert
    - https://www.linkedin.com/in/robert-harbert-575175129/
    - https://github.com/rsh249
