title: Dr. Robert S. Harbert, Ph.D.
theme: jekyll-theme-cayman
gems: [jekyll-seo-tag, jekyll-twitter-plugin]

twitter:
  username: robharbert
social:
  name: Rob Harbert
  links:
    - https://twitter.com/robharbert
    - https://www.linkedin.com/in/robert-harbert-575175129/
    - https://github.com/rsh249
    - https://scholar.google.com/citations?user=uhRJO5kAAAAJ&hl=en

image:
  feature: worldmap2.png
  
